update

diff --git a/.github/workflows/localstack.yml b/.github/workflows/localstack.yml
--- a/.github/workflows/localstack.yml
+++ b/.github/workflows/localstack.yml
@@ -10,8 +10,6 @@ jobs:
         image: localstack/localstack
         ports:
           - 4566:4566
-        options: >-
-          --network-alias localstack
         env:
           SERVICES: "lambda,s3,sts"
           DEFAULT_REGION: "ap-southeast-1"
@@ -20,7 +18,14 @@ jobs:
       - name: Wait for LocalStack to be ready
         run: |
           for i in {1..30}; do
-            curl -s http://localstack:4566/health | grep '"running": true' && break || echo "Waiting for LocalStack to start..." && sleep 2
+            health_status=$(curl -s http://localhost:4566/health)
+            echo "Health status: $health_status"
+            if [[ $health_status == *'"running": true'* ]]; then
+              echo "LocalStack is ready!"
+              break
+            fi
+            echo "Waiting for LocalStack to start..."
+            sleep 2
           done
 
       - name: Get LocalStack IP Address
@@ -37,6 +42,10 @@ jobs:
         run: |
           localstack_ip=${{ steps.get_localstack_ip.outputs.ip }}
           echo "LocalStack IP: $localstack_ip"
+          if [[ -z "$localstack_ip" ]]; then
+            echo "LocalStack IP not found, exiting..."
+            exit 1
+          fi
           for i in {1..5}; do
             aws --endpoint-url=http://$localstack_ip:4566 --region ap-southeast-1 sts get-caller-identity && break || (echo "Retrying..." && sleep 2)
           done
