update

diff --git a/.github/workflows/localstack.yml b/.github/workflows/localstack.yml
--- a/.github/workflows/localstack.yml
+++ b/.github/workflows/localstack.yml
@@ -43,7 +43,7 @@ jobs:
 
       - name: Create S3 Bucket
         run: |
-          aws --endpoint-url=http://localhost:4566 s3 mb s3://test-bucket --debug || echo "Failed to create bucket"
+          aws --endpoint-url=http://localhost:4566 --region ap-southeast-1 s3 mb s3://test-bucket --debug || echo "Failed to create bucket"
 
       - name: Show LocalStack Logs
         run: docker logs localstack
